// Labels du modèle on-device Salorie v5 (food_salorie.tflite) — 172 classes.
// EfficientNetB0, MFOOD-70 + othmanehilal + Food-101, doublons fusionnés. val_accuracy ≈ 86%.
export const FOOD_SALORIE_LABELS: string[] = [
  "amlou",
  "apple",
  "apple pie",
  "baby back ribs",
  "baghrir",
  "bahla",
  "baklava",
  "banana",
  "basbousa",
  "bastila",
  "batbout",
  "beef carpaccio",
  "beef tartare",
  "beet salad",
  "beignets",
  "better beldi",
  "bibimbap",
  "bissara",
  "bread pudding",
  "breakfast burrito",
  "briouat",
  "briouate with almonds",
  "bruschetta",
  "caesar salad",
  "cannoli",
  "caprese salad",
  "carrot cake",
  "ceviche",
  "chebakia",
  "cheese plate",
  "cheesecake",
  "chicken basstila",
  "chicken curry",
  "chicken nuggets",
  "chicken quesadilla",
  "chicken wings",
  "chicken with potatoes and olives",
  "chocolate cake",
  "chocolate mousse",
  "churros",
  "clam chowder",
  "club sandwich",
  "couscous",
  "crab cakes",
  "crackers with almonds",
  "creme brulee",
  "croissant",
  "croque madame",
  "cup cakes",
  "dates",
  "deviled eggs",
  "donuts",
  "dumplings",
  "edamame",
  "eggs benedict",
  "escargots",
  "falafel",
  "feet of beef",
  "fekkas",
  "feves with sauce",
  "filet mignon",
  "fish and chips",
  "fish and vegetables",
  "fish basstila",
  "foie gras",
  "french fries",
  "french onion soup",
  "french toast",
  "fried calamari",
  "fried rice",
  "frozen yogurt",
  "garlic bread",
  "gnocchi",
  "greek salad",
  "grilled cheese sandwich",
  "grilled salmon",
  "guacamole",
  "gyoza",
  "hamburger",
  "harcha",
  "harira",
  "hot and sour soup",
  "hot dog",
  "huevos rancheros",
  "hummus",
  "ice cream",
  "jam",
  "kaab el ghazal",
  "kaak",
  "karan",
  "khringo",
  "lasagna",
  "lentils",
  "liver with sauce",
  "lobster bisque",
  "lobster roll sandwich",
  "loubia",
  "maakouda",
  "macaroni and cheese",
  "macarons",
  "matbucha",
  "meat brochettes",
  "meatball with tomato sauce",
  "mechoui",
  "mhancha",
  "miso soup",
  "msemen",
  "mussels",
  "nachos",
  "nougat",
  "omelette",
  "onion rings",
  "orange",
  "oysters",
  "pad thai",
  "paella",
  "pancakes",
  "panna cotta",
  "pear",
  "peking duck",
  "pho",
  "pizza",
  "pork chop",
  "poutine",
  "prime rib",
  "pulled pork sandwich",
  "ramen",
  "ravioli",
  "red velvet cake",
  "rfissa",
  "rghayf",
  "risotto",
  "roasted chicken",
  "salmon",
  "samosa",
  "sashimi",
  "scallops",
  "seaweed salad",
  "seffa",
  "seffa with rice",
  "sellou",
  "sfenj",
  "shakchouka",
  "shrimp and grits",
  "snowballs",
  "spagetti",
  "spaghetti bolognese",
  "spaghetti carbonara",
  "spring rolls",
  "steak",
  "strawberry shortcake",
  "sushi",
  "sweet bread",
  "tacos",
  "tagine",
  "tagine with artichokes and peas",
  "tagine with beef",
  "tagine with quince",
  "tagine with vegetables",
  "takoyaki",
  "taktouka",
  "tanjia",
  "tiramisu",
  "tkalya",
  "tomatoes and onion salad",
  "traditional bread",
  "traditional macaroon",
  "tuna tartare",
  "waffles",
  "white beans with tomatoes",
  "zaalouk",
  "zitoun",
];
