// Labels du modele on-device Salorie (food_salorie.tflite) — 172 classes.
// ⚠ CE FICHIER EST GENERE par food4k/deployer_modele.py. Ne pas le modifier
//   a la main : il doit rester rang pour rang identique a
//   food4k/label_map_172.json, sinon un decalage d UN rang fait dire
//   « harira » a un tajine, sans aucune erreur visible.
//
// Mesure comparative face au modele precedent, sur LES MEMES images
// (corpus-ia + corpus-maghreb, jamais vus a l apprentissage) :
//     ce modele        sert 32.5 % des photos, dont 71.8 % justes
//     le precedent     servait 28.4 %, dont 62.9 % justes
// « Sert » = repond au-dessus du seuil de confiance ; en dessous, il se
// tait et la cascade prend le relais. Un modele qui sert moins mais plus
// juste est un bon echange : le cout est en latence, pas en justesse.
//
// Le chiffre precedemment inscrit ici annoncait « ≈ 86 % » ; il venait de
// l entrainement d origine, sur ses propres donnees, et d aucune mesure.
export const FOOD_SALORIE_LABELS: string[] = [
  "amlou",
  "apple",
  "apple pie",
  "baby back ribs",
  "baghrir",
  "bahla",
  "baklava",
  "banana",
  "basbousa",
  "bastila",
  "batbout",
  "beef carpaccio",
  "beef tartare",
  "beet salad",
  "beignets",
  "better beldi",
  "bibimbap",
  "bissara",
  "bread pudding",
  "breakfast burrito",
  "briouat",
  "briouate with almonds",
  "bruschetta",
  "caesar salad",
  "cannoli",
  "caprese salad",
  "carrot cake",
  "ceviche",
  "chebakia",
  "cheese plate",
  "cheesecake",
  "chicken basstila",
  "chicken curry",
  "chicken nuggets",
  "chicken quesadilla",
  "chicken wings",
  "chicken with potatoes and olives",
  "chocolate cake",
  "chocolate mousse",
  "churros",
  "clam chowder",
  "club sandwich",
  "couscous",
  "crab cakes",
  "crackers with almonds",
  "creme brulee",
  "croissant",
  "croque madame",
  "cup cakes",
  "dates",
  "deviled eggs",
  "donuts",
  "dumplings",
  "edamame",
  "eggs benedict",
  "escargots",
  "falafel",
  "feet of beef",
  "fekkas",
  "feves with sauce",
  "filet mignon",
  "fish and chips",
  "fish and vegetables",
  "fish basstila",
  "foie gras",
  "french fries",
  "french onion soup",
  "french toast",
  "fried calamari",
  "fried rice",
  "frozen yogurt",
  "garlic bread",
  "gnocchi",
  "greek salad",
  "grilled cheese sandwich",
  "grilled salmon",
  "guacamole",
  "gyoza",
  "hamburger",
  "harcha",
  "harira",
  "hot and sour soup",
  "hot dog",
  "huevos rancheros",
  "hummus",
  "ice cream",
  "jam",
  "kaab el ghazal",
  "kaak",
  "karan",
  "khringo",
  "lasagna",
  "lentils",
  "liver with sauce",
  "lobster bisque",
  "lobster roll sandwich",
  "loubia",
  "maakouda",
  "macaroni and cheese",
  "macarons",
  "matbucha",
  "meat brochettes",
  "meatball with tomato sauce",
  "mechoui",
  "mhancha",
  "miso soup",
  "msemen",
  "mussels",
  "nachos",
  "nougat",
  "omelette",
  "onion rings",
  "orange",
  "oysters",
  "pad thai",
  "paella",
  "pancakes",
  "panna cotta",
  "pear",
  "peking duck",
  "pho",
  "pizza",
  "pork chop",
  "poutine",
  "prime rib",
  "pulled pork sandwich",
  "ramen",
  "ravioli",
  "red velvet cake",
  "rfissa",
  "rghayf",
  "risotto",
  "roasted chicken",
  "salmon",
  "samosa",
  "sashimi",
  "scallops",
  "seaweed salad",
  "seffa",
  "seffa with rice",
  "sellou",
  "sfenj",
  "shakchouka",
  "shrimp and grits",
  "snowballs",
  "spagetti",
  "spaghetti bolognese",
  "spaghetti carbonara",
  "spring rolls",
  "steak",
  "strawberry shortcake",
  "sushi",
  "sweet bread",
  "tacos",
  "tagine",
  "tagine with artichokes and peas",
  "tagine with beef",
  "tagine with quince",
  "tagine with vegetables",
  "takoyaki",
  "taktouka",
  "tanjia",
  "tiramisu",
  "tkalya",
  "tomatoes and onion salad",
  "traditional bread",
  "traditional macaroon",
  "tuna tartare",
  "waffles",
  "white beans with tomatoes",
  "zaalouk",
  "zitoun",
];
