// Noms affichables des classes du modele embarque — FR et AR.
//
// ⚠ FICHIER GENERE par food4k/generer_noms_telephone.py. Ne pas editer :
//   la source est food4k/names_172.json, et trois fichiers doivent rester
//   d'accord (celui-ci, names_172.json, et assets/data/local-foods.json).
//
// POURQUOI IL EXISTE. Le modele rend un identifiant anglais (`feet of
// beef`) ; la base hors ligne et l'ecran sont en francais (`Pieds de
// veau`). Sans cette table, `localMacroForLabel` cherchait l'anglais dans
// une base francaise : 93 classes sur 172 perdaient leurs macros hors
// ligne — mesure le 09/09/2026, apres la francisation de la base.
export const FOOD_SALORIE_NOMS: Record<string, { fr: string; ar: string }> = {
  "amlou": { fr: "Amlou", ar: "أملو" },
  "apple": { fr: "Pomme", ar: "تفاح" },
  "apple pie": { fr: "Tarte aux pommes", ar: "فطيرة التفاح" },
  "baby back ribs": { fr: "Travers de porc", ar: "أضلاع لحم" },
  "baghrir": { fr: "Baghrir", ar: "البغرير" },
  "bahla": { fr: "Ghriba bahla", ar: "غريبة بهلة" },
  "baklava": { fr: "Baklava", ar: "بقلاوة" },
  "banana": { fr: "Banane", ar: "موز" },
  "basbousa": { fr: "basbousa", ar: "بسبوسة" },
  "bastila": { fr: "Pastilla", ar: "بسطيلة" },
  "batbout": { fr: "Batbout", ar: "البطبوط" },
  "beef carpaccio": { fr: "Carpaccio de bœuf", ar: "كارباتشيو لحم" },
  "beef tartare": { fr: "Tartare de bœuf", ar: "تارتار لحم" },
  "beet salad": { fr: "Salade de betteraves", ar: "سلطة الشمندر" },
  "beignets": { fr: "Beignets", ar: "بينييه" },
  "better beldi": { fr: "Smen", ar: "سمن بلدي" },
  "bibimbap": { fr: "Bibimbap", ar: "بيبيمباب" },
  "bissara": { fr: "Bissara", ar: "البصارة" },
  "bread pudding": { fr: "Pudding au pain", ar: "بودينغ الخبز" },
  "breakfast burrito": { fr: "Burrito du petit-déjeuner", ar: "بوريتو الفطور" },
  "briouat": { fr: "Briouates", ar: "بريوات" },
  "briouate with almonds": { fr: "Briouates aux amandes", ar: "بريوات باللوز" },
  "bruschetta": { fr: "Bruschetta", ar: "بروشيتا" },
  "caesar salad": { fr: "Salade César", ar: "سلطة سيزر" },
  "cannoli": { fr: "Cannoli", ar: "كانولي" },
  "caprese salad": { fr: "Salade caprese", ar: "سلطة كابريزي" },
  "carrot cake": { fr: "Gâteau aux carottes", ar: "كعكة الجزر" },
  "ceviche": { fr: "Ceviche", ar: "سيفيتشي" },
  "chebakia": { fr: "Chebakia", ar: "الشباكية" },
  "cheese plate": { fr: "Plateau de fromages", ar: "طبق الجبن" },
  "cheesecake": { fr: "Cheesecake", ar: "تشيز كيك" },
  "chicken basstila": { fr: "Pastilla au poulet", ar: "بسطيلة بالدجاج" },
  "chicken curry": { fr: "Curry de poulet", ar: "كاري الدجاج" },
  "chicken nuggets": { fr: "Nuggets de poulet", ar: "قطع الدجاج المقرمشة" },
  "chicken quesadilla": { fr: "Quesadilla au poulet", ar: "كساديا الدجاج" },
  "chicken wings": { fr: "Ailes de poulet", ar: "أجنحة الدجاج" },
  "chicken with potatoes and olives": { fr: "Poulet aux pommes de terre et olives", ar: "دجاج بالبطاطس والزيتون" },
  "chocolate cake": { fr: "Gâteau au chocolat", ar: "كعكة الشوكولاتة" },
  "chocolate mousse": { fr: "Mousse au chocolat", ar: "موس الشوكولاتة" },
  "churros": { fr: "Churros", ar: "تشوروس" },
  "clam chowder": { fr: "Chaudrée de palourdes", ar: "حساء المحار" },
  "club sandwich": { fr: "Club sandwich", ar: "كلوب ساندويتش" },
  "couscous": { fr: "couscous", ar: "كسكس" },
  "crab cakes": { fr: "Galettes de crabe", ar: "كعك السلطعون" },
  "crackers with almonds": { fr: "Craquelins aux amandes", ar: "مقرمشات باللوز" },
  "creme brulee": { fr: "Crème brûlée", ar: "كريم بروليه" },
  "croissant": { fr: "Croissant", ar: "الكرواسون" },
  "croque madame": { fr: "Croque-madame", ar: "كروك مدام" },
  "cup cakes": { fr: "Cupcakes", ar: "كب كيك" },
  "dates": { fr: "Dattes", ar: "تمر" },
  "deviled eggs": { fr: "Œufs mimosa", ar: "بيض محشي" },
  "donuts": { fr: "Donuts", ar: "دونات" },
  "dumplings": { fr: "Raviolis", ar: "دامبلينغ" },
  "edamame": { fr: "Édamame", ar: "إدامامي" },
  "eggs benedict": { fr: "Œufs bénédicte", ar: "بيض بنديكت" },
  "escargots": { fr: "Escargots", ar: "حلزون" },
  "falafel": { fr: "Falafel", ar: "فلافل" },
  "feet of beef": { fr: "Pieds de veau", ar: "كوارع" },
  "fekkas": { fr: "Fekkas", ar: "الفقاص" },
  "feves with sauce": { fr: "Fèves en sauce", ar: "فول بالصلصة" },
  "filet mignon": { fr: "Filet mignon", ar: "فيليه مينيون" },
  "fish and chips": { fr: "Fish and chips", ar: "سمك ورقائق" },
  "fish and vegetables": { fr: "Poisson aux légumes", ar: "سمك بالخضار" },
  "fish basstila": { fr: "Pastilla au poisson", ar: "بسطيلة بالسمك" },
  "foie gras": { fr: "Foie gras", ar: "كبد الأوز" },
  "french fries": { fr: "Frites", ar: "بطاطس مقلية" },
  "french onion soup": { fr: "Soupe à l'oignon", ar: "حساء البصل" },
  "french toast": { fr: "Pain perdu", ar: "توست فرنسي" },
  "fried calamari": { fr: "Calamars frits", ar: "حبار مقلي" },
  "fried rice": { fr: "Riz sauté", ar: "أرز مقلي" },
  "frozen yogurt": { fr: "Yaourt glacé", ar: "زبادي مجمد" },
  "garlic bread": { fr: "Pain à l'ail", ar: "خبز بالثوم" },
  "gnocchi": { fr: "Gnocchis", ar: "نيوكي" },
  "greek salad": { fr: "Salade grecque", ar: "سلطة يونانية" },
  "grilled cheese sandwich": { fr: "Sandwich au fromage grillé", ar: "ساندويتش الجبن" },
  "grilled salmon": { fr: "Saumon grillé", ar: "سلمون مشوي" },
  "guacamole": { fr: "Guacamole", ar: "غواكامولي" },
  "gyoza": { fr: "Gyoza", ar: "غيوزا" },
  "hamburger": { fr: "Hamburger", ar: "همبرغر" },
  "harcha": { fr: "Harcha", ar: "الحرشة" },
  "harira": { fr: "Harira", ar: "الحريرة" },
  "hot and sour soup": { fr: "Soupe aigre-piquante", ar: "حساء حار وحامض" },
  "hot dog": { fr: "Hot-dog", ar: "هوت دوغ" },
  "huevos rancheros": { fr: "Huevos rancheros", ar: "بيض رانشيروس" },
  "hummus": { fr: "Houmous", ar: "حمص" },
  "ice cream": { fr: "Glace", ar: "آيس كريم" },
  "jam": { fr: "Confiture", ar: "مربى" },
  "kaab el ghazal": { fr: "Cornes de gazelle", ar: "كعب الغزال" },
  "kaak": { fr: "Kaak", ar: "كعك" },
  "karan": { fr: "Karan", ar: "كاران" },
  "khringo": { fr: "Khringo", ar: "خرينݣو" },
  "lasagna": { fr: "Lasagnes", ar: "لازانيا" },
  "lentils": { fr: "Lentilles", ar: "عدس" },
  "liver with sauce": { fr: "Foie en chermoula", ar: "كبدة مشرملة" },
  "lobster bisque": { fr: "Bisque de homard", ar: "حساء الكركند" },
  "lobster roll sandwich": { fr: "Sandwich au homard", ar: "ساندويتش الكركند" },
  "loubia": { fr: "Haricots blancs", ar: "لوبيا" },
  "maakouda": { fr: "Maakouda", ar: "المعقودة" },
  "macaroni and cheese": { fr: "Macaronis au fromage", ar: "معكرونة بالجبن" },
  "macarons": { fr: "Macarons", ar: "ماكارون" },
  "matbucha": { fr: "Matbucha", ar: "مطبوخة" },
  "meat brochettes": { fr: "Brochettes de viande", ar: "أسياخ اللحم" },
  "meatball with tomato sauce": { fr: "Kefta à la sauce tomate", ar: "كفتة بالصلصة" },
  "mechoui": { fr: "Méchoui", ar: "المشوي" },
  "mhancha": { fr: "M'hancha", ar: "المحنشة" },
  "miso soup": { fr: "Soupe miso", ar: "حساء ميسو" },
  "msemen": { fr: "Msemen", ar: "المسمن" },
  "mussels": { fr: "Moules", ar: "بلح البحر" },
  "nachos": { fr: "Nachos", ar: "ناتشوز" },
  "nougat": { fr: "nougat", ar: "نوغة" },
  "omelette": { fr: "Omelette", ar: "أومليت" },
  "onion rings": { fr: "Rondelles d'oignon", ar: "حلقات البصل" },
  "orange": { fr: "Orange", ar: "برتقال" },
  "oysters": { fr: "Huîtres", ar: "محار" },
  "pad thai": { fr: "Pad thaï", ar: "باد تاي" },
  "paella": { fr: "Paella", ar: "باييا" },
  "pancakes": { fr: "Pancakes", ar: "بان كيك" },
  "panna cotta": { fr: "Panna cotta", ar: "بانا كوتا" },
  "pear": { fr: "Poire", ar: "إجاص" },
  "peking duck": { fr: "Canard laqué", ar: "بط بكين" },
  "pho": { fr: "Pho", ar: "فو" },
  "pizza": { fr: "Pizza", ar: "بيتزا" },
  "pork chop": { fr: "Côte de porc", ar: "ريش الخنزير" },
  "poutine": { fr: "Poutine", ar: "بوتين" },
  "prime rib": { fr: "Côte de bœuf", ar: "ضلع البقر" },
  "pulled pork sandwich": { fr: "Sandwich au porc effiloché", ar: "ساندويتش لحم مفروم" },
  "ramen": { fr: "Ramen", ar: "رامن" },
  "ravioli": { fr: "Raviolis", ar: "رافيولي" },
  "red velvet cake": { fr: "Gâteau red velvet", ar: "كعكة ريد فيلفيت" },
  "rfissa": { fr: "Rfissa", ar: "الرفيسة" },
  "rghayf": { fr: "Rghaïf", ar: "رغايف" },
  "risotto": { fr: "Risotto", ar: "ريزوتو" },
  "roasted chicken": { fr: "Poulet rôti", ar: "دجاج مشوي" },
  "salmon": { fr: "Saumon", ar: "سلمون" },
  "samosa": { fr: "Samoussa", ar: "سمبوسة" },
  "sashimi": { fr: "Sashimi", ar: "ساشيمي" },
  "scallops": { fr: "Saint-Jacques", ar: "اسكالوب" },
  "seaweed salad": { fr: "Salade d'algues", ar: "سلطة الأعشاب البحرية" },
  "seffa": { fr: "Seffa", ar: "سفة" },
  "seffa with rice": { fr: "Seffa au riz", ar: "سفة بالأرز" },
  "sellou": { fr: "Sellou", ar: "السلو" },
  "sfenj": { fr: "Sfenj", ar: "السفنج" },
  "shakchouka": { fr: "Chakchouka", ar: "شكشوكة" },
  "shrimp and grits": { fr: "Crevettes et gruau", ar: "جمبري وجريش" },
  "snowballs": { fr: "Boules de neige", ar: "كرات الثلج" },
  "spagetti": { fr: "Spaghettis", ar: "سباغيتي" },
  "spaghetti bolognese": { fr: "Spaghettis bolognaise", ar: "سباغيتي بولونيز" },
  "spaghetti carbonara": { fr: "Spaghettis carbonara", ar: "سباغيتي كاربونارا" },
  "spring rolls": { fr: "Rouleaux de printemps", ar: "لفائف الربيع" },
  "steak": { fr: "Steak", ar: "ستيك" },
  "strawberry shortcake": { fr: "Shortcake aux fraises", ar: "كعكة الفراولة" },
  "sushi": { fr: "Sushi", ar: "سوشي" },
  "sweet bread": { fr: "Pain brioché", ar: "خبز حلو" },
  "tacos": { fr: "Tacos", ar: "تاكو" },
  "tagine": { fr: "Tajine", ar: "طاجين" },
  "tagine with artichokes and peas": { fr: "Tajine aux artichauts et petits pois", ar: "طاجين بالخرشوف والبازلاء" },
  "tagine with beef": { fr: "Tajine au bœuf", ar: "طاجين باللحم" },
  "tagine with quince": { fr: "Tajine aux coings", ar: "طاجين بالسفرجل" },
  "tagine with vegetables": { fr: "Tajine aux légumes", ar: "طاجين بالخضار" },
  "takoyaki": { fr: "Takoyaki", ar: "تاكوياكي" },
  "taktouka": { fr: "Taktouka", ar: "التكتوكة" },
  "tanjia": { fr: "Tangia", ar: "الطنجية" },
  "tiramisu": { fr: "Tiramisu", ar: "تيراميسو" },
  "tkalya": { fr: "Tkalya", ar: "تقلية" },
  "tomatoes and onion salad": { fr: "Salade de tomates et oignons", ar: "سلطة الطماطم والبصل" },
  "traditional bread": { fr: "Pain traditionnel", ar: "خبز تقليدي" },
  "traditional macaroon": { fr: "Ghriba", ar: "غريبة" },
  "tuna tartare": { fr: "Tartare de thon", ar: "تارتار التونة" },
  "waffles": { fr: "Gaufres", ar: "وافل" },
  "white beans with tomatoes": { fr: "Haricots blancs à la tomate", ar: "لوبيا بيضاء بالطماطم" },
  "zaalouk": { fr: "Zaalouk", ar: "الزعلوك" },
  "zitoun": { fr: "Olives", ar: "زيتون" },
};
